version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project/benchmark-ci-tools
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Rename Existing JAR
          command: |
            if [ -f target/benchmark-ci-tools-0.0.1-SNAPSHOT.jar ]; then
              mv target/benchmark-ci-tools-0.0.1-SNAPSHOT.jar target/benchmark-ci-tools-0.0.1-SNAPSHOT-old.jar
            fi
            if [ -f target/benchmark-ci-tools-0.0.1-SNAPSHOT.jar.original ]; then
              mv target/benchmark-ci-tools-0.0.1-SNAPSHOT.jar.original target/benchmark-ci-tools-0.0.1-SNAPSHOT-old.jar.original
            fi
      - run:
          name: Build the Project
          command: mvn package
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

workflows:
  build-and-test:
    jobs:
      - test-java
